In [2]:
import pandas as pd
import numpy as np

In [3]:
df= pd.read_csv('testcsv')
#csv is comma seperated values, even if the data is seperated by a different seperator, such as ; we can use the code 
# df= pd.read_csv('testcsv', sep";")

In [4]:
df.head()

   Unnamed: 0   A   B   C   D
0           1   0   1   2   3
1           2   4   5   6   7
2           3   8   9  10  11
3           4  12  13  14  15
4           5  16  17  18  19

In [5]:
df.describe() 
# describe does not include categorical data since mean median cant be calculated.

       Unnamed: 0          A          B          C          D
count    5.000000   5.000000   5.000000   5.000000   5.000000
mean     3.000000   8.000000   9.000000  10.000000  11.000000
std      1.581139   6.324555   6.324555   6.324555   6.324555
min      1.000000   0.000000   1.000000   2.000000   3.000000
25%      2.000000   4.000000   5.000000   6.000000   7.000000
50%      3.000000   8.000000   9.000000  10.000000  11.000000
75%      4.000000  12.000000  13.000000  14.000000  15.000000
max      5.000000  16.000000  17.000000  18.000000  19.000000

In [6]:
df[df['A']>3]

   Unnamed: 0   A   B   C   D
1           2   4   5   6   7
2           3   8   9  10  11
3           4  12  13  14  15
4           5  16  17  18  19

In [10]:
from io import StringIO, BytesIO

In [11]:
data = ('col1,col2,col3\n'
        'x,y,1\n'
        'a,b,2\n'
        'c,d,3')

In [12]:
type(data)

str

In [13]:
df_buffer = pd.read_csv(StringIO(data))

In [14]:
df_buffer

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [15]:
#SELECTING SPECIFIC COLUMNS 
# Use 'usecols' to grab only the columns you need
df_cols = pd.read_csv(StringIO(data), usecols=['col1', 'col3'])

In [18]:
# SPECIFYING DATA TYPES (DTYPE) 
data_types = ('a,b,c,d\n'
              '1,2,3,4\n'
              '5,6,7,8\n'
              '9,10,11,12')

# Define different types for different columns via a dictionary
df_typed = pd.read_csv(StringIO(data_types), dtype={
    'a': np.int64,
    'b': int,
    'c': float,
    'd': 'object'
})
df_typed

   a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [19]:
# MANAGING INDEXES
# Use 'index_col' to set a specific column as the row index
index_data = ('index,a,b,c\n'
              '4,apple,bat,5.7\n'
              '8,orange,cow,10')
df_indexed = pd.read_csv(StringIO(index_data), index_col=0)

In [20]:
df_indexed

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [22]:
#Set 'index_col=False' to force Pandas not to use the first column as index [00:24:47]
df_no_index = pd.read_csv(StringIO(index_data), index_col=False)
df_no_index

   index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [23]:
#  HANDLING ESCAPE CHARACTERS [00:26:56]
# Useful for text data containing special characters
escape_data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'
df_escape = pd.read_csv(StringIO(escape_data), escapechar='\\')

In [24]:
df_escape

                               a  b
0  hello, "Bob", nice to see you  5

In [25]:
# SAVING DATA [00:16:09]
# Export DataFrame back to a CSV file
df.to_csv('output_test.csv')